on: [push, pull_request]

jobs:
  go-format:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ Checkout code
        uses: actions/checkout@v2

      - name: ğŸš§ Setup Go environment
        uses: actions/setup-go@v2.1.3

      - name: âœ… Run go fmt
        # Taken from https://stackoverflow.com/questions/42510140/check-format-for-continous-integration
        run: diff -u <(echo -n) <(gofmt -d ./)
